apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: url-shortener
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 990715
  JWT_SECRET: YourSuperSecretKeyThatIsAtLeast32CharactersLong!
  JWT_ISSUER: UrlShortener
  JWT_AUDIENCE: UrlShortenerUsers
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest